#ifndef STQ_GUI_SDL_HPP_
#define STQ_GUI_SDL_HPP_

#include <c4/error.hpp>

C4_SUPPRESS_WARNING_GCC_CLANG_PUSH
C4_SUPPRESS_WARNING_GCC_CLANG("-Wfloat-equal")
C4_SUPPRESS_WARNING_GCC_CLANG("-Wpedantic")
C4_SUPPRESS_WARNING_GCC("-Wdouble-promotion")
#include <SDL.h>
C4_SUPPRESS_WARNING_GCC_CLANG_POP

#endif /* STQ_GUI_SDL_HPP_ */
