#ifndef QUICKGUI_GUI_SDL_HPP_
#define QUICKGUI_GUI_SDL_HPP_

#include <c4/error.hpp>

C4_SUPPRESS_WARNING_GCC_CLANG_PUSH
C4_SUPPRESS_WARNING_GCC_CLANG("-Wfloat-equal")
C4_SUPPRESS_WARNING_GCC_CLANG("-Wpedantic")
C4_SUPPRESS_WARNING_GCC("-Wdouble-promotion")
C4_SUPPRESS_WARNING_CLANG("-Wold-style-cast")
#include <SDL.h>
C4_SUPPRESS_WARNING_GCC_CLANG_POP

#endif /* QUICKGUI_GUI_SDL_HPP_ */
